### ISSUE TITLE
No such file or directory: 'data/irrmaps/bsdf_256_256.bin'

### ISSUE THREAD

**Issue by yaojinzhen** [xmu-xiaoma666/X-Dreamer#3]
Hi, I successfully ran _train_x_dreamer.py_ for Geometry modeling. When I tried to run the second phase, I encountered an error where I couldn't find "bsdf_256_256.bin". I couldn't find where the file was generated in the project. How was this file generated?
The details of the error is:

```
Traceback (most recent call last):
  File "/data1/user/X-Dreamer/train_x_dreamer.py", line 690, in <module>
    geometry, mat = optimize_mesh(glctx,
  File "/data1/user/X-Dreamer/train_x_dreamer.py", line 384, in optimize_mesh
    result_image, result_dict = validate_itr(glctx, prepare_batch(next(v_it), FLAGS.train_background), geometry, opt_material, lgt, FLAGS)  #prepare_batch(next(v_it), FLAGS.background)
  File "/data1/user/X-Dreamer/train_x_dreamer.py", line 184, in validate_itr
    buffers = geometry.render(glctx, target, lgt, opt_material, if_use_bump = FLAGS.if_use_bump)
  File "/data1/user/X-Dreamer/geometry/dlmesh_x_dreamer.py", line 80, in render
    return render.render_mesh(glctx,
  File "/data1/user/X-Dreamer/render/render.py", line 267, in render_mesh
    layers += [(render_layer(rast, db, mesh, view_pos, lgt, resolution, spp, msaa, bsdf, if_normal, normal_rotate, mode, if_flip_the_normal, if_use_bump), rast)]
  File "/data1/user/X-Dreamer/render/render.py", line 197, in render_layer
    buffers = shade(gb_pos, gb_geometric_normal, gb_normal, gb_tangent, gb_texc, gb_texc_deriv,
  File "/data1/user/X-Dreamer/render/render.py", line 100, in shade
    shaded_col = lgt.shade(gb_pos, gb_normal, kd, ks, view_pos, specular = True)
  File "/data1/user/X-Dreamer/render/light.py", line 116, in shade
    self._FG_LUT = torch.as_tensor(np.fromfile('data/irrmaps/bsdf_256_256.bin', dtype=np.float32).reshape(1, 256, 256, 2), dtype=torch.float32, device='cuda')
FileNotFoundError: [Errno 2] No such file or directory: 'data/irrmaps/bsdf_256_256.bin'
```

**Comment by xmu-xiaoma666** [comment]
The missing file has been uploaded

**Comment by yaojinzhen** [comment]
> The missing file has been uploaded

thanks! this will help me a lot
